Write-Host "Installing Chocolatey..."
Set-ExecutionPolicy Bypass -Scope Process -Force; [System.Net.ServicePointManager]::SecurityProtocol = [System.Net.ServicePointManager]::SecurityProtocol -bor 3072; iex ((New-Object System.Net.WebClient).DownloadString('https://chocolatey.org/install.ps1'))
choco install chocolatey-core.extension -y

$Packages = @(
    "7zip"
    "adobedigitaleditions"
    "adobereader"
    "azure-cosmosdb-emulator"
    "azurestorageemulator"
    "cpu-z"
    "deluge"
    "docker-cli"
    "docker-desktop"
    "discord"
    "dotnet-sdk"
    "dotnet-5.0-sdk"
    "dotnet-6.0-sdk"
    "epicgameslauncher"
    "etcher"
    "firefox"
    "geforce-experience"
    "gimp"
    "git"
    "go"
    "googlechrome"
    "inkscape"
    "joplin"
    "leagueoflegends"
    "microsoft-teams"
    "microsoft-windows-terminal"
    "neovim"
    "nodejs-lts"
    "obs-studio"
    "pnpm"
    "postman"
    "potplayer"
    "powertoys"
    "putty"
    "python"
    "sharex"
    "signal"
    "spotify"
    "steam"
    "teamviewer"
    "virtualbox"
    "visualstudio2022community"
    "vscode"
    "xnviewmp"
)

foreach ($Package in $Packages) {
    Write-Host "Installing $Package..."
    choco install $Package -y
}